from common import *

SWING_RIDE = 'x.xx x.xx'

CHAPTERS = [

# ---------------- Part 5: Other styles ----------------

C(61, 5, 'The Shuffle', 'Rock, blues and swing in triplets',
  P('A <b>shuffle</b> is built on triplets with the middle note left out: long-short, long-short. It is the heartbeat of blues, early rock and roll, and a lot of rock.'),
  E('Shuffle on the hi-hat', 'Play the first and last note of each triplet.', sub=3, bpm=80, lines=dict(hh='x.x x.x x.x x.x')),
  E('The shuffle groove', 'Add bass drum on 1 and 3, snare on 2 and 4.', sub=3, bpm=90, lines=dict(hh='x.x x.x x.x x.x', sn='... o.. ... o..', bd='o.. ... o.. ...')),
  E('Shuffle with a busier foot', 'The bass drum plays the shuffle rhythm too on beat 3.', sub=3, bpm=90, lines=dict(hh='x.x x.x x.x x.x', sn='... o.. ... o..', bd='o.. ... o.o ...')),
  TIP('Feel, not math', 'A shuffle should bounce. Listen to blues records and sing along with the hi-hat before you play it.'),
),

C(62, 5, 'The Half-Time Shuffle', 'Backbeat on 3 with ghost notes',
  P('The <b>half-time shuffle</b> puts the backbeat on beat 3 and fills the space with soft <b>ghost notes</b> on the snare, played on the middle of the triplet. It is one of the most admired grooves in rock.'),
  P('Ghost notes are written in parentheses. Play them very softly, barely touching the head.'),
  E('Hands only', 'Right hand shuffles on the hi-hat; left hand plays ghost notes in between and the backbeat on 3.', sub=3, bpm=72, lines=dict(hh='x.x x.x x.x x.x', sn='.g. .g. o.. .g.')),
  E('The full groove', None, sub=3, bpm=72, lines=dict(hh='x.x x.x x.x x.x', sn='.g. .g. o.. .g.', bd='o.. ..o ... ..o')),
  TIP('Ghosts are quiet', 'If the ghost notes are as loud as the backbeat, the groove sounds cluttered. Aim for the backbeat to be at least three times louder.'),
),

C(63, 5, '12/8 Slow Blues', 'Four big beats of three',
  P('Slow blues is usually written in <b>12/8</b>: twelve eighth notes per bar, grouped in four beats of three. Count “1 2 3, 2 2 3, 3 2 3, 4 2 3”, or just feel four big beats.'),
  E('12/8 groove', 'Hi-hat on every eighth, bass drum on beats 1 and 3, snare on beats 2 and 4.', ts=[12, 8], bpm=55, lines=dict(hh='xxx xxx xxx xxx', sn='... o.. ... o..', bd='o.. ... o.. ...')),
  E('With a kick pick-up', 'An extra bass drum note leads into beat 3.', ts=[12, 8], bpm=55, lines=dict(hh='xxx xxx xxx xxx', sn='... o.. ... o..', bd='o.. ..o o.. ...')),
  TIP('Lay back', 'Slow blues needs patience. Let each backbeat land a hair late and heavy, and never rush the triplets.'),
),

C(64, 5, 'Funk Basics', 'Sixteenth-note bass drum grooves',
  P('<b>Funk</b> is built on the sixteenth-note grid. The hi-hat usually stays simple while the bass drum plays syncopated sixteenths against a strong backbeat.'),
  E('Funk groove 1', None, sub=4, bpm=90, lines=dict(hh='x.x. x.x. x.x. x.x.', sn='.... o... .... o...', bd='o..o ..o. .o.. ....')),
  E('Funk groove 2', None, sub=4, bpm=90, lines=dict(hh='x.x. x.x. x.x. x.x.', sn='.... o... .... o...', bd='o.o. ...o ..o. ....')),
  TIP('Tight and short', 'Funk notes are short and precise. Keep the hi-hat closed tight and play the bass drum with the beater bouncing off the head.'),
),

C(65, 5, 'Ghost Notes', 'The quiet notes that make grooves breathe',
  P('<b>Ghost notes</b> are extremely soft snare notes, written in parentheses. They fill in the space between the main notes and give funk and R&B grooves their texture.'),
  P('Play them from just an inch or two above the head, with your left hand relaxed. The backbeats are full strokes from high up.'),
  E('Ghost notes on the e and a', None, sub=4, bpm=80, lines=dict(hh='x.x. x.x. x.x. x.x.', sn='...g o..g .g.. o...', bd='o... .... o.o. ....')),
  E('Busier ghosts', None, sub=4, bpm=76, lines=dict(hh='x.x. x.x. x.x. x.x.', sn='.g.g o..g .g.g o..g', bd='o... ..o. o... ....')),
  TIP('Two heights', 'Backbeat: stick starts high. Ghost note: stick stays low. The contrast is everything.'),
),

C(66, 5, 'Syncopated Funk', 'Moving the snare off the beat',
  P('In more advanced funk, the snare also moves off the beat, answering the bass drum. The groove becomes a conversation between the two.'),
  E('Snare on the a of 3', None, sub=4, bpm=88, lines=dict(hh='x.x. x.x. x.x. x.x.', sn='.... o... ...o ..o.', bd='o.o. ...o .... ....')),
  E('Linear feel', 'No two limbs play at the same time.', sub=4, bpm=84, lines=dict(hh='x.x. ..x. x.x. ..x.', sn='.... o..o .... o...', bd='o..o .o.. .o.o .o..')),
  TIP('Hear it before you play it', 'Sing syncopated grooves out loud first, with sounds for each drum (“boom”, “chick”, “ts”). If you can sing it, your limbs will follow.'),
),

C(67, 5, 'Reggae: The One Drop', 'Everything lands on 3',
  P('The <b>one drop</b> is the classic reggae groove. The bass drum and snare land together on beat 3 only, and beat 1 is left empty. The snare is usually played as a <b>cross-stick</b>: the tip of the stick rests on the head and the shaft clicks on the rim.'),
  E('One drop', 'Snare (cross-stick) and bass drum together on 3.', bpm=70, lines=dict(hh='xxxx xxxx', sn='.... o...', bd='.... o...')),
  E('One drop with open hat', None, bpm=70, lines=dict(hh='xxxx xxxO', sn='.... o...', bd='.... o...')),
  TIP('Resist beat 1', 'Every instinct says to play the bass drum on 1. Don’t. The empty 1 is what makes the groove float.'),
),

C(68, 5, 'Bossa Nova', 'Brazilian groove with a two-bar pattern',
  P('The <b>bossa nova</b> comes from Brazil. Straight eighths on the hi-hat or ride, a gentle bass drum, the hi-hat foot on 2 and 4, and a two-bar cross-stick pattern on the snare.'),
  E('Bossa nova', 'Cross-stick pattern: 1, the & of 2 and 4 in the first bar; 2 and the & of 3 in the second.', bars=2, bpm=120, lines=dict(rd='xxxx xxxx xxxx xxxx', sn='o..o ..o. ..o. .o..', bd='o..o o..o o..o o..o', hf='..x. ..x. ..x. ..x.')),
  TIP('Soft and relaxed', 'Bossa nova is gentle music. Play everything at half your normal volume and let it breathe.'),
),

C(69, 5, 'Samba', 'Driving Brazilian groove in two',
  P('<b>Samba</b> is fast, joyful and felt in two. The bass drum imitates the big <i>surdo</i> drum with a pattern on 1, the a of 1, 2 and the a of 2, while the hands play steady sixteenths.'),
  E('Samba feet', 'The bass drum surdo pattern with the hi-hat foot on the &s.', sub=4, ts=[2, 4], bars=2, bpm=80, lines=dict(bd='o..o o..o o..o o..o', hf='..x. ..x. ..x. ..x.')),
  E('Samba groove', 'Add sixteenths on the snare with accents.', sub=4, ts=[2, 4], bars=2, bpm=80, lines=dict(sn='oooo oooo oooo oooo', bd='o..o o..o o..o o..o', hf='..x. ..x. ..x. ..x.'), st='RLRL RLRL RLRL RLRL', acc='...> ..>. ...> ..>.'),
  TIP('Feet first', 'Get the bass drum and hi-hat foot pattern going on their own until it feels like walking. Then add the hands.'),
),

C(70, 5, 'The 6/8 Afro-Cuban Bell', 'A timeless pattern',
  P('Much Afro-Cuban and West African music is built on a <b>6/8 bell pattern</b>: seven notes spread over twelve eighth notes (1, 3, 5, 6, 8, 10, 12). On the drum set it is often played on the ride cymbal or its bell.'),
  E('Bell pattern', 'The ride plays the bell pattern; the bass drum plays the four big beats softly.', ts=[12, 8], bpm=70, lines=dict(rd='x.x .xx .x. x.x', bd='o.. o.. o.. o..')),
  E('With hi-hat foot', 'Hi-hat foot on beats 2 and 4.', ts=[12, 8], bpm=70, lines=dict(rd='x.x .xx .x. x.x', bd='o.. o.. o.. o..', hf='... x.. ... x..')),
  TIP('Sing the bell', 'Sing the pattern until you can repeat it for a whole minute without thinking. Then add the feet.'),
),

C(71, 5, 'The Train Beat', 'Country’s locomotive groove',
  P('The <b>train beat</b> imitates a train on the tracks: constant sixteenths on the snare with accents on beats 2 and 4. It drives a lot of country and rockabilly.'),
  E('Train beat', 'Accents on 2 and 4, everything else soft.', sub=4, bpm=88, lines=dict(sn='oooo oooo oooo oooo', bd='o... .... o... ....'), st='RLRL RLRL RLRL RLRL', acc='.... >... .... >...'),
  E('Train beat with accents on the &s too', None, sub=4, bpm=88, lines=dict(sn='oooo oooo oooo oooo', bd='o... .... o... ....'), st='RLRL RLRL RLRL RLRL', acc='..>. >.>. ..>. >.>.'),
  TIP('Brushes', 'The train beat sounds great with brushes. If you have a pair, try it with them.'),
),

C(72, 5, 'Country Two-Step', 'Boom-chick',
  P('The <b>two-step</b> is the basic country groove: bass drum on 1 and 3, snare (often a cross-stick) on 2 and 4. It sounds like “boom-chick, boom-chick”.'),
  E('Two-step', None, bpm=120, lines=dict(hh='x.x. x.x.', sn='..o. ..o.', bd='o... o...')),
  E('Two-step with the & of 4', None, bpm=120, lines=dict(hh='x.x. x.x.', sn='..o. ..o.', bd='o... o..o')),
  TIP('Lock with the bass player', 'In country, the bass guitar usually plays on 1 and 3 with your bass drum. Listen for it and play exactly with it.'),
),

C(73, 5, 'The Motown Beat', 'Snare on every beat',
  P('Many 1960s soul and pop records put the snare on <b>all four beats</b>, often doubled with a tambourine. It gives the music a bright, bouncing, danceable drive.'),
  E('Motown', None, bpm=110, lines=dict(hh='xxxx xxxx', sn='o.o. o.o.', bd='o... o..o')),
  E('Motown with bass drum pick-ups', None, bpm=110, lines=dict(hh='xxxx xxxx', sn='o.o. o.o.', bd='o..o o..o')),
  TIP('Even snares', 'All four snare notes are equal. Don’t accent 2 and 4 out of habit.'),
),

C(74, 5, 'Grooves in 3/4', 'Waltzes and slow three',
  P('Songs in <b>3/4</b> have three beats per bar. The simplest groove puts the bass drum on 1 and the snare on 2 and 3; a slower, heavier feel puts the snare only on 3.'),
  E('Waltz groove', None, ts=[3, 4], bpm=100, lines=dict(hh='xxxxxx', sn='..o.o.', bd='o.....')),
  E('Slow 3/4', 'Snare only on beat 3.', ts=[3, 4], bpm=70, lines=dict(hh='xxxxxx', sn='....o.', bd='o..o..')),
  TIP('Count out loud', 'After years of 4/4, your body wants a fourth beat. Count “1 2 3” aloud until it feels natural.'),
),

C(75, 5, 'The 6/8 Ballad', 'Two big beats of three',
  P('Many slow ballads are in <b>6/8</b>: six eighth notes per bar, felt as two big beats. The bass drum plays beat 1 and the snare plays beat 4 (the second big beat).'),
  E('6/8 ballad', None, ts=[6, 8], bars=2, bpm=60, lines=dict(hh='xxxxxx xxxxxx', sn='...o.. ...o..', bd='o..... o....o')),
  E('6/8 with toms', 'Floor tom on the eighth notes for a bigger sound.', ts=[6, 8], bars=2, bpm=60, lines=dict(t2='oooooo oooooo', sn='...o.. ...o..', bd='o..... o.....')),
  TIP('Rock the boat', 'Feel 6/8 as two slow swings: 1-2-3, 4-5-6. The music rocks back and forth.'),
),

# ---------------- Part 6: Jazz ----------------

C(76, 6, 'The Swing Feel', 'Long-short eighths',
  P('In jazz, pairs of eighth notes are not played evenly. The first is longer and the second shorter, like the first and last notes of a triplet. This is the <b>swing feel</b>.'),
  P('Jazz is written with ordinary eighth notes, and the players swing them automatically. Compare the two examples below: they sound the same.'),
  E('Written as triplets', 'The first and last notes of each triplet.', sub=3, bpm=100, lines=dict(sn='o.o o.o o.o o.o'), st='R_L R_L R_L R_L'),
  E('Written as swing eighths', 'Ordinary eighth notes, played swung.', swing=True, bpm=100, lines=dict(sn='oooo oooo'), st='RLRL RLRL'),
  TIP('How much swing?', 'Slow jazz swings heavily; very fast jazz swings less and the eighths get closer to even. Listen to records at different tempos.'),
),

C(77, 6, 'The Jazz Ride Pattern', 'Ding, ding-a-ding',
  P('The <b>ride pattern</b> is the foundation of jazz drumming: quarter notes on 1 and 3, and “ding-a” on 2 and 4 (the skip note falls on the swung & of 2 and 4).'),
  E('Ride pattern', 'Sing it: “ding, ding-a-ding, ding-a”.', swing=True, bpm=110, lines=dict(rd=SWING_RIDE)),
  E('Two bars', None, swing=True, bars=2, bpm=130, lines=dict(rd=SWING_RIDE + ' ' + SWING_RIDE)),
  TIP('The ride leads the band', 'In jazz, the ride cymbal is the time. Bass players lock to it. Keep it steady and let everything else float on top.'),
),

C(78, 6, 'Hi-Hat on 2 and 4', 'The left foot joins in',
  P('Add the hi-hat pedal on beats <b>2 and 4</b>. It clicks together with the ride on those beats and gives the band a strong reference point.'),
  E('Ride and hi-hat foot', None, swing=True, bpm=120, lines=dict(rd=SWING_RIDE, hf='..x. ..x.')),
  TIP('A crisp chick', 'Press the pedal down firmly and keep it closed until the next note. The sound should be a short “chick”.'),
),

C(79, 6, 'Feathering the Bass Drum', 'Felt, not heard',
  P('Jazz drummers often play the bass drum very softly on all four beats. This is called <b>feathering</b>. It should be felt more than heard, supporting the bass player without covering them.'),
  E('Ride, hi-hat and feathered bass drum', 'The bass drum notes are ghost notes: barely touch the head.', swing=True, bpm=120, lines=dict(rd=SWING_RIDE, hf='..x. ..x.', bd='g.g. g.g.')),
  TIP('Heel down', 'Feathering is easiest heel down, using just the ankle. Let the beater touch the head and come straight back off.'),
),

C(80, 6, 'Comping on the Snare', 'Talking to the band',
  P('While the ride and hi-hat keep time, the left hand adds short snare notes called <b>comping</b> (from “accompanying”). Comping answers the soloist and pushes the band.'),
  P('This chapter follows the idea behind Jim Chapin’s independence method: keep the time pattern steady and move a single comp note around. The exercises are my own.'),
  E('Comp on the & of 2', None, swing=True, bpm=110, lines=dict(rd=SWING_RIDE, sn='...o ....', hf='..x. ..x.')),
  E('Comp on the & of 4', None, swing=True, bpm=110, lines=dict(rd=SWING_RIDE, sn='.... ...o', hf='..x. ..x.')),
  E('Comp on the & of 1 and 3', 'These fall between ride notes: the hardest ones.', swing=True, bpm=100, lines=dict(rd=SWING_RIDE, sn='.o.. .o..', hf='..x. ..x.')),
  TIP('The ride doesn’t notice', 'If your ride pattern changes when the snare comes in, you’re not independent yet. Slow down until the ride stays exactly the same.'),
),

C(81, 6, 'Comping on the Bass Drum', 'The right foot talks too',
  P('Now move the comping to the bass drum. Jazz drummers use louder bass drum comps, sometimes called <b>bombs</b>, to kick the band into a new phrase.'),
  E('Bass drum on the & of 2', None, swing=True, bpm=110, lines=dict(rd=SWING_RIDE, hf='..x. ..x.', bd='...o ....')),
  E('Bass drum on the & of 4', None, swing=True, bpm=110, lines=dict(rd=SWING_RIDE, hf='..x. ..x.', bd='.... ...o')),
  E('Snare and bass drum together', 'Snare on the & of 1, bass drum on the & of 3.', swing=True, bpm=100, lines=dict(rd=SWING_RIDE, sn='.o.. ....', hf='..x. ..x.', bd='.... .o..')),
  TIP('Bombs are rare', 'A bass drum bomb is a big event. Use one to set up a new section, not every bar.'),
),

C(82, 6, 'Triplet Comping', 'Comping on the middle of the triplet',
  P('Writing jazz in triplets lets us put comp notes on the <b>middle</b> of the triplet too, a place swing eighths can’t reach. It gives a rolling, conversational feel.'),
  E('Ride in triplets', 'The ride pattern written in triplets.', sub=3, bpm=110, lines=dict(rd='x.. x.x x.. x.x', hf='... x.. ... x..')),
  E('Comp on “trip” of 2', None, sub=3, bpm=100, lines=dict(rd='x.. x.x x.. x.x', sn='... .o. ... ...', hf='... x.. ... x..')),
  E('Triplet comping line', 'A longer comp figure under the ride.', sub=3, bpm=96, lines=dict(rd='x.. x.x x.. x.x', sn='..o .o. ..o ...', hf='... x.. ... x..')),
  TIP('Count the triplet', 'Count “1 trip-let 2 trip-let” while the ride plays. Find the “trip” before you play anything on it.'),
),

C(83, 6, 'The Jazz Waltz', 'Swing in three',
  P('The <b>jazz waltz</b> is swing in 3/4. A common ride pattern is “ding, ding-a-ding”: beat 1, then beat 2 with a skip note into beat 3.'),
  E('Jazz waltz', None, swing=True, ts=[3, 4], bars=2, bpm=140, lines=dict(rd='x.xxx. x.xxx.', hf='..x... ..x...', bd='g..... g.....')),
  TIP('Feel one big beat', 'At fast tempos, the jazz waltz is often felt as one big beat per bar. Let the ride flow and don’t accent every beat.'),
),

C(84, 6, 'Brushes', 'Sweeps and taps',
  P('<b>Brushes</b> are fans of thin wires (or nylon) used instead of sticks for soft music. The left brush usually <b>sweeps</b> in circles across the snare to make a steady “shhh”, while the right brush taps the ride pattern on the snare.'),
  UL('Left hand: sweep a slow circle on the head, clockwise, one full circle every two beats.',
     'Right hand: tap the swing ride pattern on the snare.',
     'Hi-hat foot on 2 and 4, bass drum feathered.'),
  E('The right-hand brush pattern', 'The ride pattern played on the snare with a brush. (The left-hand sweep can’t be written as notes.)', swing=True, bpm=100, lines=dict(sn='o.oo o.oo', hf='..x. ..x.', bd='g.g. g.g.')),
  TIP('Listen to the masters', 'Brush playing is learned by ear. Listen to jazz ballads and try to copy the sound of the sweep.'),
),

C(85, 6, 'Trading Fours', 'Taking turns soloing',
  P('In jazz, the drummer often <b>trades fours</b> with the soloists: the band plays four bars, then the drummer solos for four bars, back and forth. Here is a shorter version: one bar of time, one bar of solo.'),
  E('Time, then solo', 'One bar of ride pattern, one bar of triplet solo on the snare and toms.', sub=3, bars=2, bpm=100,
    lines=dict(rd='x.. x.x x.. x.x ... ... ... ...', sn='... ... ... ... ooo ... o.o ...', t1='... ... ... ... ... oo. ... ...', t2='... ... ... ... ... ..o ... o..', hf='... x.. ... x.. ... x.. ... x..', bd='g.. g.. g.. g.. o.. ... ... ..o')),
  TIP('Keep the form', 'While you solo, keep counting the bars and hear the song’s melody in your head. The band needs you to come back in at exactly the right place.'),
),
]
