from common import *

G8 = dict(hh='xxxx xxxx', sn='..o. ..o.', bd='o... o...')

CHAPTERS = [

# ---------------- Part 7: Fills ----------------

C(86, 7, 'What Is a Fill?', 'Leading the band into the next section',
  P('A <b>fill</b> is a short break from the groove that leads into the next part of a song. Fills usually come at the end of a phrase (every 4 or 8 bars) and land on a crash cymbal with the bass drum on beat 1.'),
  P('A fill should take up <b>exactly</b> the same time as the groove it replaces. The most common mistake is rushing.'),
  E('One bar of groove, one bar of fill', 'The fill is four quarter notes around the kit. Listen for the crash when it loops back to the top.', bars=2, bpm=84,
    lines=dict(cr='x... .... .... ....', hh='.xxx xxxx .... ....', sn='..o. ..o. o... ....', t1='.... .... ..o. ....', t2='.... .... .... o.o.', bd='o... o... o... o...')),
  TIP('Count the phrase', 'Count bars out loud while you play: “1-2-3-4, 2-2-3-4, 3-2-3-4, FILL-2-3-4”. You’ll always know when the fill is coming.'),
),

C(87, 7, 'Quarter-Note Fills', 'Simple and strong',
  P('The simplest fills use <b>quarter notes</b>. They are slow enough to move easily around the kit and they sound big.'),
  E('Snare to floor tom', 'Three beats of groove, then one quarter on the floor tom.', sub=2, bars=2, bpm=84,
    lines=dict(cr='x... .... .... ....', hh='.xxx xxxx xxxx xx..', sn='..o. ..o. ..o. ....', t2='.... .... .... ..o.', bd='o... o... o... o...')),
  E('Full-bar quarter fill', 'Snare, rack tom, floor tom, floor tom.', sub=2, bars=2, bpm=84,
    lines=dict(cr='x... .... .... ....', hh='.xxx xxxx .... ....', sn='..o. ..o. o... ....', t1='.... .... ..o. ....', t2='.... .... .... o.o.', bd='o... o... .... ....')),
  TIP('Move the whole arm', 'Going from the snare to the floor tom, lead with the elbow. The stick follows.'),
),

C(88, 7, 'Eighth-Note Fills', 'Two per beat',
  P('<b>Eighth-note fills</b> are twice as busy. Keep the sticking alternating (R L R L) and move down the toms from high to low.'),
  E('One-beat eighth fill', None, bars=2, bpm=84,
    lines=dict(cr='x... .... .... ....', hh='.xxx xxxx xxxx xx..', sn='..o. ..o. ..o. ....', t2='.... .... .... ..oo', bd='o... o... o... o...'), st='____ ____ ____ __RL'),
  E('Two-beat eighth fill', 'Four eighth notes on the floor tom on beats 3 and 4.', bars=2, bpm=84,
    lines=dict(cr='x... .... .... ....', hh='.xxx xxxx xxxx ....', sn='..o. ..o. ..o. ....', t1='.... .... .... ....', t2='.... .... .... oooo', bd='o... o... o... ....'), st='____ ____ ____ RLRL'),
  E('Full-bar eighth fill', None, bars=2, bpm=84,
    lines=dict(cr='x... .... .... ....', hh='.xxx xxxx .... ....', sn='..o. ..o. oo.. ....', t1='.... .... ..oo ....', t2='.... .... .... oooo', bd='o... o... .... ....'), st='____ ____ RLRL RLRL'),
  TIP('Lead with the right', 'With alternating sticking, the right hand plays every number and the left every &. Plan your moves so the right hand gets to each new drum first.'),
),

C(89, 7, 'Sixteenth-Note Fills', 'The classic rock fill',
  P('<b>Sixteenth-note fills</b> are the sound of rock drumming. Four notes per drum, moving from high to low, is the classic shape.'),
  E('One-beat sixteenth fill', 'Four sixteenths on the snare on beat 4.', sub=4, bars=2, bpm=80,
    lines=dict(cr='x... .... .... .... .... .... .... ....', hh='..x. x.x. x.x. x.x. x.x. x.x. x.x. ....', sn='.... o... .... o... .... o... .... oooo', bd='o... .... o... .... o... .... o... ....'), st='____ ____ ____ ____ ____ ____ ____ RLRL'),
  E('Around the kit', 'Snare, rack tom, floor tom, floor tom.', sub=4, bars=2, bpm=76,
    lines=dict(cr='x... .... .... .... .... .... .... ....', hh='..x. x.x. x.x. x.x. .... .... .... ....', sn='.... o... .... o... oooo .... .... ....', t1='.... .... .... .... .... oooo .... ....', t2='.... .... .... .... .... .... oooo oooo', bd='o... .... o.o. .... .... .... .... ....'), st='____ ____ ____ ____ RLRL RLRL RLRL RLRL'),
  TIP('Crash with both', 'Land the crash with your right hand and the bass drum together, exactly on 1.'),
),

C(90, 7, 'Triplet Fills', 'Rolling around the kit',
  P('<b>Triplet fills</b> have a rolling, rounded sound that fits shuffles, blues and slow 12/8 songs perfectly.'),
  E('Shuffle with a triplet fill', 'Triplets down the toms on beat 4.', sub=3, bars=2, bpm=84,
    lines=dict(cr='x.. ... ... ... ... ... ... ...', hh='..x x.x x.x x.x x.x x.x x.x ...', sn='... o.. ... o.. ... o.. ... o..', t1='... ... ... ... ... ... ... .o.', t2='... ... ... ... ... ... ... ..o', bd='o.. ... o.. ... o.. ... o.. ...'), st='___ ___ ___ ___ ___ ___ ___ RLR'),
  E('Two-beat triplet fill', None, sub=3, bars=2, bpm=80,
    lines=dict(cr='x.. ... ... ... ... ... ... ...', hh='..x x.x x.x x.x x.x x.x ... ...', sn='... o.. ... o.. ... o.. ooo ...', t2='... ... ... ... ... ... ... ooo', bd='o.. ... o.. ... o.. ... ... ...'), st='___ ___ ___ ___ ___ ___ RLR LRL'),
  TIP('The lead hand switches', 'Triplets with alternating sticking start on the right, then the left, then the right. Practice them slowly so each beat’s first note is clear.'),
),

C(91, 7, 'Fills with Space', 'Rests and bass drum',
  P('A fill doesn’t need a note on every sixteenth. Leaving <b>space</b>, or putting the bass drum into the fill, often sounds more musical than a wall of notes.'),
  E('Hands and feet', 'Snare, rack tom, then bass drum, repeated.', sub=4, bars=2, bpm=76,
    lines=dict(cr='x... .... .... .... .... .... .... ....', hh='..x. x.x. x.x. x.x. x.x. x.x. .... ....', sn='.... o... .... o... .... o... o... o...', t1='.... .... .... .... .... .... .o.. .o..', bd='o... .... o... .... o... .... ..o. ..o.'), st='____ ____ ____ ____ ____ ____ RL__ RL__'),
  E('Space fill', 'A few well-placed notes instead of many.', sub=4, bars=2, bpm=80,
    lines=dict(cr='x... .... .... .... .... .... .... ....', hh='..x. x.x. x.x. x.x. x.x. x.x. .... ....', sn='.... o... .... o... .... o... o..o ....', t2='.... .... .... .... .... .... .... o.o.', bd='o... .... o... .... o... .... .... ....')),
  TIP('Less can be more', 'The best drummers often play the simplest fills. Ask yourself what the song needs, not what your hands can do.'),
),

C(92, 7, 'Landing the Fill', 'Crash, bass drum and the next 1',
  P('The last note of a fill and the first note after it are what the band hears most. Make the landing strong and exactly on time.'),
  UL('Crash cymbal and bass drum together on beat 1.',
     'Don’t leave a gap after the fill: the groove starts again right away.',
     'Some fills end on the & of 4 with the crash on 1; others end with a note on 1 itself.'),
  E('Ending on the a of 4', 'A sixteenth fill that runs right up to the crash.', sub=4, bars=2, bpm=80,
    lines=dict(cr='x... .... .... .... .... .... .... ....', hh='..x. x.x. x.x. x.x. x.x. x.x. x.x. ....', sn='.... o... .... o... .... o... .... oo..', t2='.... .... .... .... .... .... .... ..oo', bd='o... .... o... .... o... .... o... ....')),
  E('Leaving the & of 4 empty', 'The fill stops early, and the silence before the crash builds tension.', sub=4, bars=2, bpm=80,
    lines=dict(cr='x... .... .... .... .... .... .... ....', hh='..x. x.x. x.x. x.x. x.x. x.x. x.x. ....', sn='.... o... .... o... .... o... .... o...', bd='o... .... o... .... o... .... o... ....')),
  TIP('Practice the landing', 'Practice just the last beat of the fill and the crash, over and over, until the landing is automatic.'),
),

C(93, 7, 'Fill Workshop', 'Make your own',
  P('Every fill in this part was built the same way: pick a <b>rhythm</b> (quarters, eighths, sixteenths or triplets), pick a <b>length</b> (one beat, two beats or a whole bar), and pick a <b>path</b> around the drums.'),
  TABLE(('CHOOSE', 'OPTIONS'), ('Rhythm', 'Quarters, eighths, sixteenths, triplets, or a mix'), ('Length', '1 beat, 2 beats, 1 bar'), ('Path', 'High to low, low to high, snare only, back and forth'), ('Extras', 'Flams, accents, bass drum notes, rests')),
  E('Flam fill', 'Flams on the toms mixed with sixteenths.', sub=4, bars=2, bpm=72,
    lines=dict(cr='x... .... .... .... .... .... .... ....', hh='..x. x.x. x.x. x.x. .... .... .... ....', sn='.... o... .... o... f.oo .... .... ....', t1='.... .... .... .... .... f.oo .... ....', t2='.... .... .... .... .... .... f.oo f.oo', bd='o... .... o... .... .... .... .... ....')),
  E('Paradiddle fill', 'Paradiddle sticking with the right hand on the floor tom.', sub=4, bars=2, bpm=72,
    lines=dict(cr='x... .... .... .... .... .... .... ....', hh='..x. x.x. x.x. x.x. .... .... .... ....', sn='.... o... .... o... .o.. o.oo .o.. o.oo', t2='.... .... .... .... o.oo .o.. o.oo .o..', bd='o... .... o... .... .... .... .... ....'), st='____ ____ ____ ____ RLRR LRLL RLRR LRLL'),
  TIP('Write them down', 'When you make up a fill you like, write it down. In a few weeks you’ll have your own fill book.'),
),

# ---------------- Part 8: Reading & musicianship ----------------

C(94, 8, 'Syncopated Reading', 'Reading off the beat',
  P('Syncopated reading lines train you to read rhythms that fall off the beat. Play these on the snare while the bass drum keeps quarter notes.'),
  E('Line 1', None, bars=2, bpm=72, lines=dict(sn='o..o ..o. .o.o o...', bd='o.o. o.o. o.o. o.o.')),
  E('Line 2', 'Ties across the beat.', bars=2, bpm=68, lines=dict(sn='.o.o o..o .oo. o...', bd='o.o. o.o. o.o. o.o.'), ties=[3]),
  E('Line 3', 'Sixteenth-note syncopation.', sub=4, bars=2, bpm=60, lines=dict(sn='o..o ..o. .o.o o... .oo. o..o ..oo o...', bd='o... o... o... o... o... o... o... o...')),
  TIP('Keep the foot going', 'The bass drum on every beat is your anchor. If the foot stops, the reading has taken over. Slow down until both work together.'),
),

C(95, 8, 'Reading Lines as Grooves', 'One page, many exercises',
  P('A single reading line becomes a whole new exercise when you play it on a different instrument under a groove. Here, the same rhythm is played on the snare with a rock groove, and on the bass drum under the jazz ride.'),
  E('On the snare over a rock groove', 'Hi-hat eighths, bass drum on 1 and 3, the reading line on the snare.', bars=2, bpm=80, lines=dict(hh='xxxx xxxx xxxx xxxx', sn='..oo .o.. o..o ..o.', bd='o... o... o... o...')),
  E('On the bass drum under the ride', 'Swing ride and hi-hat foot, the same rhythm on the bass drum.', swing=True, bars=2, bpm=110, lines=dict(rd='x.xx x.xx x.xx x.xx', hf='..x. ..x. ..x. ..x.', bd='..oo .o.. o..o ..o.')),
  TIP('Three ways, every page', 'For any reading line in this book, try it on the snare, on the bass drum, and split between snare and toms.'),
),

C(96, 8, 'Reading a Drum Chart', 'Repeats, endings and slashes',
  P('In a band you will often read a <b>drum chart</b>: a map of the song rather than every note. Charts use a few special symbols.'),
  TABLE(('SYMBOL', 'MEANING'),
    ('Repeat signs (thick bar with two dots)', 'Play the bars between the signs again.'),
    ('1st and 2nd endings', 'Play the 1st ending the first time, skip to the 2nd ending on the repeat.'),
    ('Slashes (/ / / /)', 'Play time: your own groove in the style of the song.'),
    ('One-bar repeat (a slash with two dots)', 'Play the previous bar again.'),
    ('Section letters (A, B, C) or names', 'Verse, chorus, bridge.'),
    ('Rhythms above the staff', 'Band “hits” or “kicks”: play these with the band, usually with a crash and bass drum.')),
  P('The most important skill is catching <b>hits</b>: rhythms the whole band plays together. Keep time, and play the hit with a crash and bass drum.'),
  E('Catching hits', 'Time on the hi-hat, then band hits on 1 and the & of 2 in the second bar.', bars=2, bpm=96,
    lines=dict(hh='xxxx xxxx .... ....', cr='.... .... x..x ....', sn='..o. ..o. .... ..o.', bd='o... o... o..o o...')),
  TIP('Read ahead', 'While you play one bar, your eyes should already be on the next. Charts reward drummers who look ahead.'),
),

C(97, 8, 'Song Form and Playing with a Band', 'Listening is the job',
  P('Most songs are built from sections that repeat: <b>intro, verse, chorus, verse, chorus, bridge, chorus, ending</b>. Sections are usually 4, 8 or 16 bars. As the drummer, you help the band know where they are.'),
  UL('Change your sound between sections: hi-hat in the verse, ride or open hi-hat in the chorus.',
     'Play a fill at the end of a section to announce the next one.',
     'Keep fills short in the verse where the singer needs space.',
     'Watch the other players. Eye contact is how bands stay together.'),
  E('Verse to chorus', 'A verse bar on the hi-hat with a small fill, then the chorus with crash and ride.', sub=4, bars=2, bpm=84,
    lines=dict(hh='x.x. x.x. x.x. .... .... .... .... ....', sn='.... o... .... oo.. .... o... .... o...', t2='.... .... .... ..oo .... .... .... ....', cr='.... .... .... .... x... .... .... ....', rd='.... .... .... .... ..x. x.x. x.x. x.x.', bd='o... .... o.o. .... o... .... o.o. ....')),
  TIP('Serve the song', 'The best compliment a drummer can get is “that felt great”. Nobody remembers a flashy fill if the groove wasn’t solid.'),
),

C(98, 8, 'Tuning Your Drums', 'Getting a good sound',
  P('Well-tuned drums are easier and more fun to play. Every drum has two heads: the <b>batter</b> head you hit, and the <b>resonant</b> head on the other side.'),
  OL('Loosen all the tension rods. Seat the head by pressing gently in the middle.',
     'Tighten each rod finger-tight, then use the drum key in a star pattern (across the drum, not around it), a half turn at a time.',
     'Tap an inch in front of each rod. Adjust until every spot sounds the same pitch.',
     'Tune the resonant head the same way. Equal or slightly higher than the batter gives a long, open tone.',
     'Toms: high to low with clear steps between them. Snare: batter medium-tight, snare-side head tighter.'),
  E('Listening test', 'Rack tom, floor tom and snare. Your toms should sound like clear steps down.', sub=1, bars=2, bpm=60, lines=dict(t1='o... ....', t2='.o.. ....', sn='..o. o...', bd='...o .o..')),
  TIP('Small turns', 'Make tiny adjustments, a quarter turn or less. Big turns overshoot the sound you’re looking for.'),
),

C(99, 8, 'Caring for Your Kit', 'Stands, heads, cymbals and sticks',
  P('A drum set lasts decades with a little care.'),
  UL('<b>Heads:</b> replace them when they sound dead or have dents. Batter heads wear out faster than resonant heads.',
     '<b>Cymbals:</b> never overtighten the wing nut. Cymbals need to move, and a clamped cymbal can crack. Use felts and sleeves on the stands.',
     '<b>Stands and pedals:</b> tighten loose screws, oil the bass drum pedal springs now and then.',
     '<b>Sticks:</b> replace chipped or cracked sticks before they splinter.',
     '<b>Moving:</b> use cases or bags. Most damage happens in transport.',
     '<b>Your ears:</b> the most important part of your kit. Wear hearing protection.'),
  E('Sound check', 'Play each drum and cymbal in turn to check everything sounds right before you play.', sub=1, bars=2, bpm=66,
    lines=dict(cr='x... ....', rd='.x.. ....', hh='..x. ....', t1='...o ....', sn='.... o...', t2='.... .o..', bd='.... ..o.', hf='.... ...x')),
  TIP('Check before you play', 'Before every gig or lesson, play a quick sound check. You’ll catch a loose wing nut or a slipping pedal before it matters.'),
),

C(100, 8, 'Where to Go Next', 'Keep playing, keep listening',
  P('If you’ve worked through this book, you can hold the sticks, read rhythms, play the main rudiments, groove in many styles, play fills and read a chart. That’s a real foundation. Here’s how to keep growing.'),
  UL('<b>Play along with records.</b> Pick songs you love and learn the drum parts by ear.',
     '<b>Play with other people.</b> Nothing teaches time and listening like a band.',
     '<b>Go deeper into a style.</b> Jazz, funk, Latin and metal each have whole books of their own. There are excellent method books for every style.',
     '<b>Keep your routine.</b> Rudiments and reading, a little every day.',
     '<b>Find a teacher.</b> A good teacher spots in minutes what you might take months to notice.'),
  E('Graduation piece', 'A groove, a fill and a crash: everything together.', sub=4, bars=2, bpm=84,
    lines=dict(cr='x... .... .... .... .... .... .... ....', hh='..x. x.x. x.xO x.x. x.x. x.x. .... ....', sn='.... o..g .g.. o... .... o..g f.oo ....', t1='.... .... .... .... .... .... .... oo..', t2='.... .... .... .... .... .... .... ..oo', bd='o... ..o. o..o .... o... ..o. .... ....')),
  TIP('Thank you', 'Thanks for learning with the Amadeus School of Drums. Now go make some music.'),
),
]
