from common import *

CHAPTERS = [

C(1, 1, 'How to Use This Book', 'Pages, examples and the player',
  P('This book takes you from your first stroke to reading real drum charts. It is written for students working on their own at home, with a practice pad or a drum set, and for teachers who want material to hand out.'),
  P('Each chapter explains one idea, shows it on the staff, and gives you a <b>playable example</b>. Press <b>Play</b> and the example counts you in for one bar, then plays with a metronome click while each note lights up as it sounds. Use <b>+</b> and <b>&minus;</b> to change the tempo, and switch the metronome off when you are ready to keep time yourself.'),
  E('Try the player', 'Four quarter notes on the snare. Press Play, listen to the count-in, then play along.', sub=1, bpm=70, lines=dict(sn='o o o o'), st='R L R L'),
  H('How to work through a chapter'),
  OL('Read the explanation all the way through.',
     'Press Play and <b>listen</b> to the example two or three times without playing.',
     'Count it out loud while it plays.',
     'Play along slowly, then turn the tempo up a little at a time.',
     'Switch the metronome off and play it on your own.'),
  TIP('Go in order', 'The chapters build on each other. If a chapter feels hard, go back one or two and play those examples again. That is normal, and it is how everyone learns.'),
  BOX('About the exercises', 'Some parts of this book follow the teaching order of classic drum methods, and those chapters say so. All the explanations and exercises are my own. For the complete original courses, get the books themselves.', 'NOTE'),
),

C(2, 1, 'Meet the Drum Set', 'The parts of the kit and what they do',
  P('A basic drum set has four or five drums (bass drum, snare, one or two rack toms and a floor tom) and two or three cymbals. Every drummer sets up a little differently, but the parts are the same. This book uses a four-piece kit.'),
  TABLE(('PART', 'WHAT IT DOES'),
    ('Bass drum', 'The big drum on the floor, played with your right foot on a pedal. It is the low heartbeat of the band.'),
    ('Snare drum', 'The drum between your knees. Metal wires (the snares) under the bottom head give it its crack. Most backbeats are played here.'),
    ('Rack tom', 'Mounted above the bass drum. Higher-pitched, used mostly in fills.'),
    ('Floor tom', 'Stands on its own legs to your right. Deep and booming.'),
    ('Hi-hat', 'Two cymbals on a stand with a pedal. Played with sticks, with your left foot, or both. Closed it is tight and crisp; open it sizzles.'),
    ('Ride cymbal', 'A large cymbal on your right used to “ride” a steady pattern, especially in jazz.'),
    ('Crash cymbal', 'Used for big accents, usually at the start of a new section.')),
  E('A tour of the kit', 'Each drum and cymbal in turn: bass drum, snare, rack tom, floor tom, hi-hat, ride, crash, hi-hat foot.', sub=1, bars=2, bpm=66,
    lines=dict(bd='o... ....', sn='.o.. ....', t1='..o. ....', t2='...o ....', hh='.... x...', rd='.... .x..', cr='.... ..x.', hf='.... ...x')),
  TIP('Left-handed?', 'Many left-handed drummers set up a mirror-image kit: bass drum on the left foot, hi-hat on the right. Everything in this book works the same way; just swap “right” and “left”.'),
),

C(3, 1, 'Holding the Sticks', 'Matched grip and the fulcrum',
  P('This book uses <b>matched grip</b>: both hands hold the sticks the same way. It is what most drummers use on the drum set today.'),
  OL('Find the balance point about a third of the way up from the butt end of the stick.',
     'Pinch the stick at that point between the pad of your thumb and the first joint of your index finger. This pinch is called the <b>fulcrum</b>.',
     'Let your other fingers wrap loosely around the stick. They guide it; they do not squeeze it.',
     'Turn your hands so the backs face mostly up (German grip) or halfway to the side (American grip). Both are fine.',
     'Leave a small gap between the stick and your palm so it can move freely.'),
  P('A good grip lets the stick bounce off the drum on its own. If you squeeze, the stick chokes and your hands get tired fast.'),
  E('Alternating strokes', 'Right, left, right, left in steady eighth notes. Keep both sticks at the same height and the sound of both hands the same.', bpm=72, lines=dict(sn='oooo oooo'), st='RLRL RLRL'),
  TIP('Check yourself', 'Look at your hands in a mirror while you play. Both sticks should make the same shape in the air. If one hand looks different, slow down and match it to the other.'),
),

C(4, 1, 'Setting Up and Sitting', 'Throne height, posture and pedals',
  P('A comfortable setup makes everything easier. Sit on the drum throne so your thighs slope very slightly down toward your knees. Your back is straight but relaxed, and your feet rest flat on the pedals.'),
  UL('<b>Snare</b> just above your lap, tilted slightly toward you.',
     '<b>Hi-hat</b> a few inches above the snare, on your left.',
     '<b>Bass drum pedal</b> where your right foot falls naturally.',
     '<b>Toms and cymbals</b> close enough to reach without stretching or leaning.'),
  H('Playing the pedals'),
  P('There are two main ways to play the bass drum. <b>Heel down</b> keeps the heel on the pedal and moves the foot from the ankle; it is quieter and more controlled. <b>Heel up</b> lifts the heel and uses the whole leg; it is louder and used in most rock. Try both.'),
  E('Just the feet', 'Bass drum on every beat, hi-hat foot closing on 2 and 4. Let your feet settle into a steady walk.', sub=1, bpm=72, lines=dict(bd='oooo', hf='.x.x')),
  TIP('Stay relaxed', 'If your shoulders creep up or your jaw clenches, stop, breathe out, and start again slower. Tension is the biggest enemy of good time.'),
),

C(5, 1, 'The Four Basic Strokes', 'Full, down, tap and up strokes',
  P('Every note you play is one of four strokes. Knowing them lets you play loud and soft notes next to each other without effort.'),
  TABLE(('STROKE', 'STARTS', 'ENDS', 'USE'),
    ('Full', 'High', 'High', 'Loud notes in a row'),
    ('Down', 'High', 'Low', 'A loud note followed by soft ones'),
    ('Tap', 'Low', 'Low', 'Soft notes'),
    ('Up', 'Low', 'High', 'A soft note that prepares a loud one')),
  P('The trick is where the stick <b>stops</b>. After a down stroke, catch the stick low, just above the head. Before an accent, lift the stick during the soft note that comes first (the up stroke).'),
  E('Full strokes', 'All notes loud, sticks starting and ending high.', sub=1, bpm=70, lines=dict(sn='o o o o'), acc='> > > >', st='R L R L'),
  E('Down, tap, tap, up', 'An accent at the start of each beat. Down stroke on the accent, taps in the middle, up stroke on the last note of the group.', sub=4, bpm=60,
    lines=dict(sn='oooo oooo oooo oooo'), acc='>... >... >... >...', st='RLRL RLRL RLRL RLRL'),
  TIP('Two heights only', 'Use just two heights: high for accents (about 12 inches), low for taps (about 2 inches). Clear heights make clear dynamics.'),
),

C(6, 1, 'Reading the Drum Staff', 'Where each drum is written',
  P('Drum music is written on a five-line staff, like other music, but the lines and spaces stand for instruments instead of pitches. The double bar at the start is the <b>percussion clef</b>.'),
  KEY,
  P('Cymbals are usually written with an <b>x</b> for a note head. Drums use round note heads. Notes for your hands have stems pointing up; notes for your feet have stems pointing down.'),
  E('Top to bottom', 'Each instrument in the key, from the top of the staff to the bottom.', sub=1, bars=2, bpm=66,
    lines=dict(cr='x... ....', hh='.x.. ....', rd='..x. ....', t1='...o ....', sn='.... o...', t2='.... .o..', bd='.... ..o.', hf='.... ...x')),
  TIP('Read vertically', 'Notes stacked on one stem happen at the same time. Read the stack from bottom to top: feet first, then hands.'),
),

C(7, 1, 'Beats, Bars and Time Signatures', '4/4, 3/4 and 2/4',
  P('Music is organized into a steady pulse called the <b>beat</b>. Beats are grouped into <b>bars</b> (also called measures), separated by bar lines.'),
  P('The <b>time signature</b> at the start tells you how. The top number is how many beats are in each bar. The bottom number tells you which note gets one beat; a 4 means the quarter note.'),
  E('4/4 time', 'Four beats per bar, the most common time signature. The accent marks beat 1.', sub=1, bpm=80, lines=dict(sn='o o o o'), acc='> . . .'),
  E('3/4 time', 'Three beats per bar: the waltz.', sub=1, ts=[3, 4], bpm=90, lines=dict(sn='o o o'), acc='> . .'),
  E('2/4 time', 'Two beats per bar: the march.', sub=1, ts=[2, 4], bpm=100, lines=dict(sn='o o'), acc='> .'),
  TIP('Feel the one', 'Beat 1 of every bar is called the <b>downbeat</b>. Musicians use it to stay together. Always know where the 1 is.'),
),

C(8, 1, 'Using a Metronome', 'Your practice partner',
  P('A metronome clicks a perfectly steady beat. Playing with one trains you to keep steady time, which is the most important job a drummer has.'),
  P('Tempo is measured in <b>beats per minute</b> (BPM). 60 BPM is one beat each second. Most songs are somewhere between 70 and 140.'),
  E('Lock in with the click', 'Quarter notes at 60 BPM. Try to make your stick land so exactly on the click that the click disappears.', sub=1, bpm=60, lines=dict(sn='o o o o'), st='R L R L'),
  H('Ways to practice with the click'),
  UL('Start slower than you think you need to.',
     'Play the example four times perfectly before raising the tempo by 5.',
     'Try hearing the click as beats 2 and 4 instead of every beat. Set the tempo to half and think of the click as the backbeat.',
     'Turn the metronome off for a bar, then back on. Are you still together?'),
  TIP('Burying the click', 'When you are perfectly in time, the click gets hard to hear because your note covers it. That is the goal.'),
),

C(9, 1, 'How to Practice', 'Short, focused, every day',
  P('Twenty minutes every day beats two hours once a week. Your hands and brain learn during the days in between, so regular practice adds up fast.'),
  PRACTICE(('5 min', 'Warm up: single and double strokes, slowly.'), ('10 min', 'Today’s chapter: the examples, slow then faster.'), ('5 min', 'Review one older chapter you like.'), ('5 min', 'Just play: grooves, fills, or along with a song.')),
  E('Warm-up', 'Eighth notes, alternating hands. Start at 60 and raise the tempo 5 at a time.', bpm=60, lines=dict(sn='oooo oooo'), st='RLRL RLRL'),
  UL('Practice slowly enough to play it right every time.',
     'Stop when you make the same mistake twice. Slow down and fix that one spot.',
     'Record yourself on a phone now and then. You will hear things you miss while playing.',
     'End each session with something fun.'),
  TIP('Protect your ears', 'Real drums are loud enough to damage hearing over time. Wear earplugs or isolating headphones when you practice on a kit.'),
),

C(10, 1, 'Counting Out Loud', 'The habit that makes reading easy',
  P('Counting out loud connects what you see on the page to what you play. It feels awkward at first. Do it anyway: every good reader started this way.'),
  TABLE(('NOTE', 'NOTES PER BEAT', 'SAY'), ('Quarter notes', '1', '1 2 3 4'), ('Eighth notes', '2', '1 & 2 & 3 & 4 &'), ('Sixteenth notes', '4', '1 e & a, 2 e & a…'), ('Triplets', '3', '1 trip-let, 2 trip-let…')),
  E('Count quarters', 'Say “1 2 3 4” as you play.', sub=1, bpm=70, lines=dict(sn='o o o o')),
  E('Count eighths', 'Say “1 & 2 & 3 & 4 &”.', bpm=70, lines=dict(sn='oooo oooo'), st='RLRL RLRL'),
  E('Count sixteenths', 'Say “1 e & a”. “e” rhymes with “me”, “a” sounds like “uh”.', sub=4, bpm=60, lines=dict(sn='oooo oooo oooo oooo'), st='RLRL RLRL RLRL RLRL'),
  TIP('Say the rests too', 'Keep counting through rests, even though you don’t play. The count is what keeps you in the right place.'),
),

# ---------------- Part 2: Reading rhythm ----------------

C(11, 2, 'Quarter Notes', 'One beat each',
  P('A <b>quarter note</b> is a filled-in note head with a stem. In 4/4 it gets one beat, so there are four in a bar.'),
  E('Alternating', 'Right, left, right, left.', sub=1, bars=2, bpm=72, lines=dict(sn='oooo oooo'), st='RLRL RLRL'),
  E('Right-hand lead', 'Right hand only. Keep every stroke the same height.', sub=1, bars=2, bpm=72, lines=dict(sn='oooo oooo'), st='RRRR RRRR'),
  E('Doubles', 'Two with each hand.', sub=1, bars=2, bpm=72, lines=dict(sn='oooo oooo'), st='RRLL RRLL'),
  E('On the kit', 'Hi-hat quarter notes with the right hand, bass drum with the foot on 1 and 3.', sub=1, bars=2, bpm=76, lines=dict(hh='xxxx xxxx', bd='o.o. o.o.')),
  TIP('Even is everything', 'Record yourself playing Example 11.1. Every note should be the same volume and exactly the same distance apart.'),
),

C(12, 2, 'Half Notes and Whole Notes', 'Two beats and four beats',
  P('Longer notes have hollow (open) note heads. A <b>half note</b> has a stem and lasts two beats. A <b>whole note</b> has no stem and lasts four beats, a whole bar of 4/4.'),
  P('A drum can’t hold a sound the way a violin can, so you play the note once and then keep counting until its time is up. The count is what matters.'),
  E('Half notes', 'Play on 1 and 3. Count 2 and 4 out loud.', sub=1, bars=2, bpm=72, lines=dict(sn='o-o- o-o-'), st='R_L_ R_L_'),
  E('Whole notes', 'Play on 1, then count 2 3 4.', sub=1, bars=2, bpm=72, lines=dict(sn='o--- o---'), st='R___ L___'),
  E('Mixing values', 'Half, quarter, quarter; then a whole note.', sub=1, bars=2, bpm=72, lines=dict(sn='o-oo o---'), st='R_LR L___'),
  TIP('The dotted half', 'A dot after a note adds half its value. A dotted half note lasts three beats: that fills a whole bar of 3/4.'),
  E('Dotted half in 3/4', 'One note, then count 2 and 3.', sub=1, ts=[3, 4], bars=2, bpm=90, lines=dict(sn='o-- o--'), st='R__ L__'),
),

C(13, 2, 'Rests', 'Counted silence',
  P('A <b>rest</b> means don’t play, but keep counting. Every note value has a matching rest.'),
  TABLE(('REST', 'LOOKS LIKE', 'LASTS'), ('Quarter rest', 'A zigzag', '1 beat'), ('Half rest', 'A block sitting on the middle line', '2 beats'), ('Whole rest', 'A block hanging from the 4th line', 'A whole bar')),
  E('Quarter rests', 'Play on 1 and 3, rest on 2 and 4.', sub=1, bars=2, bpm=72, lines=dict(sn='o.o. o.o.'), st='R_L_ R_L_'),
  E('Rests first', 'Rest on 1 and 2 (a half rest), then play 3 and 4.', sub=1, bars=2, bpm=72, lines=dict(sn='..oo ..oo'), st='__RL __RL'),
  E('A bar of silence', 'Four notes, then a whole bar of rest. Keep counting through it.', sub=1, bars=2, bpm=72, lines=dict(sn='oooo ....'), st='RLRL ____'),
  TIP('Rests are active', 'Lift your stick slightly during a rest, ready for the next note. Freezing in place makes the next note late.'),
),

C(14, 2, 'Eighth Notes', 'Two per beat',
  P('<b>Eighth notes</b> split each beat in half. A single eighth note has a flag; two or more in the same beat are joined by a <b>beam</b>. Count them “1 & 2 & 3 & 4 &”.'),
  E('Straight eighths', 'Alternate hands.', bars=2, bpm=70, lines=dict(sn='oooo oooo oooo oooo'), st='RLRL RLRL RLRL RLRL'),
  E('Right-hand eighths on the hi-hat', 'This is the right hand of the basic rock beat.', bars=2, bpm=80, lines=dict(hh='xxxx xxxx xxxx xxxx', bd='o... o... o... o...')),
  E('Eighths in groups', 'Quarter notes and eighth notes together. Keep counting the &s.', bars=2, bpm=70, lines=dict(sn='o.oo o.oo oo.. oooo'), st='R_RL R_RL RL__ RLRL'),
  TIP('Feel the &', 'Tap your foot on the numbers. The & is exactly when your foot comes up.'),
),

C(15, 2, 'Eighth Rests', 'Half a beat of silence',
  P('An <b>eighth rest</b> looks like a small 7 with a dot on its top-left. It is half a beat of silence. When an eighth rest is followed by an eighth note, the note falls on the &.'),
  E('Rest on the &', 'Play on the numbers only. (These look like quarter notes, because an eighth plus an eighth rest is one beat.)', bars=2, bpm=72, lines=dict(sn='o.o. o.o. o.o. o.o.'), st='R_L_ R_L_ R_L_ R_L_'),
  E('Play on the &', 'Rest on the numbers, play on the &s. Tap your foot on the numbers to keep your place.', bars=2, bpm=66, lines=dict(sn='.o.o .o.o .o.o .o.o', bd='o.o. o.o. o.o. o.o.')),
  E('Mixed', 'A reading line with eighth rests in different places.', bars=2, bpm=66, lines=dict(sn='o..o .ooo o.o. .o.o')),
  TIP('Say “rest”', 'When counting Example 15.2, say the numbers quietly and the &s loudly: “(1) AND (2) AND”.'),
),

C(16, 2, 'Reading Quarters and Eighths', 'Your first reading lines',
  P('Now put quarter notes, eighth notes and their rests together. These reading lines are like short sentences: read them one beat at a time.'),
  E('Line 1', None, bars=2, bpm=72, lines=dict(sn='o.oo o.o. oooo o...')),
  E('Line 2', None, bars=2, bpm=72, lines=dict(sn='oo.o o.oo .oo. o.o.')),
  E('Line 3', None, bars=2, bpm=72, lines=dict(sn='.oo. oo.o o.oo .o..')),
  E('Line 4', 'A longer line with a whole-note ending.', bars=2, sub=2, bpm=72, lines=dict(sn='oooo .o.o o--- ----')),
  TIP('Clap it first', 'Clap each line while counting before you play it. If you can clap it, you can play it.'),
),

C(17, 2, 'Sixteenth Notes', 'Four per beat',
  P('<b>Sixteenth notes</b> split each beat into four. They have two beams (or two flags). Count them “1 e & a, 2 e & a”.'),
  E('Straight sixteenths', 'Alternate hands, very even.', sub=4, bpm=60, lines=dict(sn='oooo oooo oooo oooo'), st='RLRL RLRL RLRL RLRL'),
  E('With the bass drum', 'Sixteenths in the hands, quarter notes on the bass drum.', sub=4, bpm=60, lines=dict(sn='oooo oooo oooo oooo', bd='o... o... o... o...')),
  E('Eighths to sixteenths', 'Two beats of eighths, two beats of sixteenths. The hands double their speed but the beat stays the same.', sub=4, bpm=60, lines=dict(sn='o.o. o.o. oooo oooo'), st='R_L_ R_L_ RLRL RLRL'),
  TIP('Small and relaxed', 'Faster notes need smaller strokes, not more effort. Let the sticks bounce.'),
),

C(18, 2, 'Sixteenth-Note Rhythms, Part 1', 'The gallop and the reverse gallop',
  P('Most sixteenth-note rhythms are combinations of sixteenths and eighths inside one beat. Two of the most common:'),
  UL('<b>“1 e &”</b>: two sixteenths then an eighth. It sounds like “quick-ly go”.',
     '<b>“1 & a”</b>: an eighth then two sixteenths. It sounds like a gallop.'),
  E('1 e &', 'Two sixteenths and an eighth in every beat.', sub=4, bpm=60, lines=dict(sn='ooo. ooo. ooo. ooo.'), st='RLR_ RLR_ RLR_ RLR_'),
  E('1 & a', 'An eighth and two sixteenths in every beat.', sub=4, bpm=60, lines=dict(sn='o.oo o.oo o.oo o.oo'), st='R_RL R_RL R_RL R_RL'),
  E('Mix them', 'Straight sixteenths, 1 e &, 1 & a, and eighths.', sub=4, bpm=60, lines=dict(sn='oooo ooo. o.oo o.o.')),
  TIP('Keep the hands moving', 'An easy way to keep perfect time: move your hands in constant sixteenths (R L R L) and only let the stick touch the drum on the notes that are written.'),
),

C(19, 2, 'Sixteenth-Note Rhythms, Part 2', 'The rest of the combinations',
  P('Here are the other ways to fill one beat with sixteenths and eighths.'),
  TABLE(('RHYTHM', 'COUNT', 'WHAT IT IS'),
    ('16th, 8th, 16th', '1 e _ a', 'Sometimes called the “syncopated” sixteenth.'),
    ('Dotted 8th, 16th', '1 _ _ a', 'The dot makes the first note three sixteenths long.'),
    ('16th, dotted 8th', '1 e _ _', 'The reverse: short, then long.'),
    ('16th rest, three 16ths', '_ e & a', 'Starts just after the beat.')),
  E('1 e a', None, sub=4, bpm=60, lines=dict(sn='oo.o oo.o oo.o oo.o')),
  E('1 a (dotted eighth and sixteenth)', None, sub=4, bpm=60, lines=dict(sn='o..o o..o o..o o..o')),
  E('1 e (sixteenth and dotted eighth)', None, sub=4, bpm=60, lines=dict(sn='oo.. oo.. oo.. oo..')),
  E('e & a', None, sub=4, bpm=60, lines=dict(sn='.ooo .ooo .ooo .ooo', bd='o... o... o... o...')),
  TIP('Use the constant motion', 'Keep the sticking R L R L on the sixteenth grid for all of these. Your right hand will always be on the numbers and the &s; your left on the e’s and a’s.'),
),

C(20, 2, 'Off-Beat Sixteenths', 'Playing on the e and the a',
  P('The hardest sixteenths to feel are the ones on the <b>e</b> and the <b>a</b>, because they fall between the numbers and the &s. The bass drum on the beat helps you feel where you are.'),
  E('Just the e', 'A sixteenth rest, then a dotted eighth.', sub=4, bpm=56, lines=dict(sn='.o.. .o.. .o.. .o..', bd='o... o... o... o...')),
  E('Just the a', 'A dotted eighth rest, then a sixteenth.', sub=4, bpm=56, lines=dict(sn='...o ...o ...o ...o', bd='o... o... o... o...')),
  E('e and a', None, sub=4, bpm=56, lines=dict(sn='.o.o .o.o .o.o .o.o', bd='o... o... o... o...')),
  E('Reading line', 'All the sixteenth rhythms mixed together.', sub=4, bars=2, bpm=56, lines=dict(sn='o.oo .o.o ooo. o..o .ooo oo.. o.o. o...')),
  TIP('Hands moving, sticks silent', 'Keep your hands going R L R L even when there is a rest. The motion keeps your place for you.'),
),

C(21, 2, 'Dotted Notes', 'The dot adds half',
  P('A dot after a note makes it half again as long.'),
  TABLE(('NOTE', 'PLAIN', 'DOTTED'), ('Half note', '2 beats', '3 beats'), ('Quarter note', '1 beat', '1½ beats'), ('Eighth note', '½ beat', '¾ beat')),
  P('The <b>dotted quarter followed by an eighth</b> is one of the most common rhythms in music. The eighth lands on the & of the second beat.'),
  E('Dotted quarter and eighth', 'Count “1 (2) & 3 4”.', bars=2, bpm=72, lines=dict(sn='o--o o.o. o--o o...')),
  E('Dotted eighth and sixteenth', 'Long-short, long-short.', sub=4, bpm=60, lines=dict(sn='o..o o..o o..o o..o')),
  E('Dotted half in 4/4', 'Three beats long, then a quarter note.', sub=1, bars=2, bpm=72, lines=dict(sn='o--o o--o')),
  TIP('Count the smaller notes', 'When a rhythm has dots, count in the smallest note value you see. For dotted quarters, count eighth notes: “1 & 2 & 3 & 4 &”.'),
),

C(22, 2, 'Ties', 'Joining two notes into one',
  P('A <b>tie</b> is a curved line joining two notes of the same drum. Play the first note only, and let it last for the length of both. Ties are used when a note needs to cross the middle of a bar or a beat.'),
  E('Tied across the beat', 'The & of 2 is tied to beat 3, so you play on the & and nothing on 3.', bars=2, bpm=70, lines=dict(sn='o.oo o.o. o.oo o...'), ties=[3, 11]),
  E('Tied across the bar line', 'The & of 4 is tied to beat 1 of the next bar. Play the &, then nothing on 1.', bars=2, bpm=70, lines=dict(sn='o.o. o.oo o.o. o.o.'), ties=[7]),
  P('On drums, ties show up most often with rolls and cymbal crashes, where the sound really does keep going.'),
  TIP('Count, don’t guess', 'Say every count out loud and only play the first note of a tie. Your count will tell you exactly where the next note comes in.'),
),

C(23, 2, 'Eighth-Note Triplets', 'Three per beat',
  P('A <b>triplet</b> fits three notes into one beat instead of two. It is marked with a 3 over the beam. Count “1 trip-let, 2 trip-let”.'),
  E('Triplets', 'Alternate hands. Notice that the lead hand switches every beat.', sub=3, bpm=60, lines=dict(sn='ooo ooo ooo ooo'), st='RLR LRL RLR LRL'),
  E('Accent the beat', 'Accent the first note of each triplet.', sub=3, bpm=60, lines=dict(sn='ooo ooo ooo ooo'), st='RLR LRL RLR LRL', acc='>.. >.. >.. >..'),
  E('Triplets over the bass drum', 'Bass drum on every beat. Feel three even notes inside each beat.', sub=3, bpm=60, lines=dict(sn='ooo ooo ooo ooo', bd='o.. o.. o.. o..'), st='RLR LRL RLR LRL'),
  TIP('Say it', '“Straw-ber-ry, straw-ber-ry” has the same rhythm as triplets.'),
),

C(24, 2, 'Triplet Partials', 'Triplets with rests',
  P('Leave out parts of the triplet and you get new rhythms. These are the building blocks of the shuffle and of jazz.'),
  TABLE(('PLAY', 'COUNT', 'SOUNDS LIKE'), ('1st and 3rd', '1 _ let', 'The shuffle: long-short'), ('2nd and 3rd', '_ trip let', 'Pick-up into the next beat'), ('1st and 2nd', '1 trip _', 'Short-long')),
  E('1st and 3rd: the shuffle', None, sub=3, bpm=66, lines=dict(sn='o.o o.o o.o o.o'), st='R_L R_L R_L R_L'),
  E('2nd and 3rd', None, sub=3, bpm=60, lines=dict(sn='.oo .oo .oo .oo', bd='o.. o.. o.. o..')),
  E('Reading line', 'Mixed triplet partials.', sub=3, bars=2, bpm=60, lines=dict(sn='ooo o.o .oo o.. o.o ooo .oo o..')),
  TIP('Keep the triplet going inside', 'Think all three notes of the triplet even when you only play two. Your hands can keep moving R L R.'),
),

C(25, 2, 'Accents and Dynamics', 'Loud, soft and everything between',
  P('An <b>accent</b> (&gt;) means play that note louder than the others. <b>Dynamics</b> tell you the overall volume: <i>p</i> (piano) is soft, <i>mf</i> (mezzo-forte) is medium, <i>f</i> (forte) is loud. A hairpin that opens means get louder (crescendo); one that closes means get softer (decrescendo).'),
  E('Accent on each beat', None, sub=4, bpm=60, lines=dict(sn='oooo oooo oooo oooo'), st='RLRL RLRL RLRL RLRL', acc='>... >... >... >...'),
  E('Accent on the e', None, sub=4, bpm=60, lines=dict(sn='oooo oooo oooo oooo'), st='RLRL RLRL RLRL RLRL', acc='.>.. .>.. .>.. .>..'),
  E('Accent on the &', None, sub=4, bpm=60, lines=dict(sn='oooo oooo oooo oooo'), st='RLRL RLRL RLRL RLRL', acc='..>. ..>. ..>. ..>.'),
  E('Accent on the a', None, sub=4, bpm=60, lines=dict(sn='oooo oooo oooo oooo'), st='RLRL RLRL RLRL RLRL', acc='...> ...> ...> ...>'),
  TIP('Soft notes make accents', 'Most students play accents too loud and the other notes too loud as well. Keep the unaccented notes really soft, and the accents will pop out without any strain.'),
),
]
