from common import *

S16 = 'RLRL RLRL RLRL RLRL'

CHAPTERS = [

# ---------------- Part 3: Rudiments ----------------

C(26, 3, 'What Are Rudiments?', 'The drummer’s scales',
  P('<b>Rudiments</b> are short sticking patterns that every drummer learns, the way piano players learn scales. They build control, speed and evenness, and nearly every fill and groove you will ever play is made from them.'),
  P('There are forty standard rudiments. They fall into four families:'),
  TABLE(('FAMILY', 'BUILT FROM', 'EXAMPLES'), ('Rolls', 'Single, double or buzzed strokes', 'Single stroke roll, double stroke roll, five-stroke roll'), ('Diddles', 'A mix of singles and doubles', 'Paradiddle, double paradiddle, paradiddle-diddle'), ('Flams', 'A soft grace note just before a main note', 'Flam, flam tap, flam accent, flamacue'), ('Drags', 'Two soft grace notes before a main note', 'Drag, single drag tap')),
  E('A taste: single strokes', 'The most basic rudiment of all. Right, left, right, left.', sub=4, bpm=60, lines=dict(sn='oooo oooo oooo oooo'), st=S16),
  TIP('Slow, then fast, then slow', 'The classic way to practice a rudiment: start very slowly, speed up gradually to as fast as you can play it cleanly, then slow back down. This is called “open-close-open”.'),
),

C(27, 3, 'The Single Stroke Roll', 'R L R L',
  P('The <b>single stroke roll</b> is simply alternating hands: R L R L. It sounds easy, but making both hands sound exactly the same takes years to master.'),
  E('Building speed', 'Quarter notes, then eighths, then sixteenths, all with alternating sticking.', sub=4, bars=2, bpm=60, lines=dict(sn='o... o... o.o. o.o. oooo oooo oooo oooo'), st='R___ L___ R_L_ R_L_ RLRL RLRL RLRL RLRL'),
  E('Left-hand lead', 'The same roll, starting with the left hand. Your weaker hand needs this.', sub=4, bpm=60, lines=dict(sn='oooo oooo oooo oooo'), st='LRLR LRLR LRLR LRLR'),
  E('Accented singles', 'Accent every third note. The accent moves between the hands.', sub=3, bpm=60, lines=dict(sn='ooo ooo ooo ooo'), st='RLR LRL RLR LRL', acc='>.. >.. >.. >..'),
  TIP('Listen, don’t look', 'Close your eyes and listen. If you can tell which hand is playing, the two hands aren’t even yet.'),
),

C(28, 3, 'The Double Stroke Roll', 'R R L L',
  P('The <b>double stroke roll</b> plays two notes with each hand: R R L L. Played fast, it becomes the smooth “open roll” used in marching and concert music.'),
  P('The second note of each double is played by letting the stick <b>bounce</b> and helping it with your fingers. The goal is for the second note to be as loud as the first.'),
  E('Doubles', None, sub=4, bpm=60, lines=dict(sn='oooo oooo oooo oooo'), st='RRLL RRLL RRLL RRLL'),
  E('Singles to doubles', 'Two beats of singles, two beats of doubles. Keep the same hand motion.', sub=4, bpm=60, lines=dict(sn='oooo oooo oooo oooo'), st='RLRL RLRL RRLL RRLL'),
  E('Written as a roll', 'Slashes through the stem mean “play a roll”. Three slashes on a quarter note means fast doubles for the whole beat.', sub=4, bpm=60, lines=dict(sn='w... w... w... o...'), acc='.... .... .... >...'),
  TIP('Accent the second note', 'To even out your doubles, practice them with an accent on the second note of each pair: R <b>R</b> L <b>L</b>.'),
),

C(29, 3, 'The Single Paradiddle', 'R L R R, L R L L',
  P('The <b>paradiddle</b> combines two singles and a double: R L R R, L R L L. Because it ends with a double, the lead hand switches every group. Say it: “pa-ra-did-dle”.'),
  E('Paradiddles', 'Accent the first note of each group.', sub=4, bpm=60, lines=dict(sn='oooo oooo oooo oooo'), st='RLRR LRLL RLRR LRLL', acc='>... >... >... >...'),
  E('Paradiddle groove', 'Right hand on the hi-hat, left hand on the snare, with the paradiddle sticking. It turns a rudiment into a groove.', sub=4, bpm=70, lines=dict(hh='x.xx .x.. x.xx .x..', sn='.o.. o.oo .o.. o.oo', bd='o... .... o... ....'), st='RLRR LRLL RLRR LRLL'),
  TIP('Inversions', 'Start the paradiddle on different notes and you get new patterns: R R L R (starting on the double) is great for grooves.'),
),

C(30, 3, 'The Double Paradiddle', 'R L R L R R, L R L L',
  P('The <b>double paradiddle</b> adds two more singles: R L R L R R, L R L R L L. The six-note groups fit naturally into triplets.'),
  E('Double paradiddles in triplets', 'Accent the first note of each six-note group.', sub=3, bpm=60, lines=dict(sn='ooo ooo ooo ooo'), st='RLR LRR LRL RLL', acc='>.. ... >.. ...'),
  E('In 6/8', 'One double paradiddle per bar of 6/8.', ts=[6, 8], bars=2, bpm=60, lines=dict(sn='oooooo oooooo'), st='RLRLRR LRLRLL', acc='>..... >.....'),
  TIP('Count in two', 'Each six-note group takes two beats. Count “1 trip-let 2 trip-let” and put the accent on 1.'),
),

C(31, 3, 'The Paradiddle-Diddle', 'R L R R L L',
  P('The <b>paradiddle-diddle</b> is two singles followed by two doubles: R L R R L L. Unlike the paradiddle, it always starts with the same hand.'),
  E('Paradiddle-diddles', None, sub=3, bpm=60, lines=dict(sn='ooo ooo ooo ooo'), st='RLR RLL RLR RLL', acc='>.. ... >.. ...'),
  E('Around the toms', 'Singles on the snare, first double on the rack tom, second double on the floor tom.', sub=3, bpm=60, lines=dict(sn='oo. ... oo. ...', t1='..o o.. ..o o..', t2='... .oo ... .oo', bd='o.. o.. o.. o..'), st='RLR RLL RLR RLL'),
  TIP('A drummer’s favorite', 'Played fast around the kit, the paradiddle-diddle is behind many famous fills. Once it’s smooth, try moving the doubles to different drums.'),
),

C(32, 3, 'The Flam', 'A grace note just before the main note',
  P('A <b>flam</b> is two notes played almost together: a very soft <b>grace note</b> followed immediately by a loud main note in the other hand. It sounds like one fat note: “fl-AM”.'),
  P('Start with one stick high (it will play the main note) and one stick low, just above the head (the grace note). Drop both at once. The low stick lands first because it has less distance to travel.'),
  E('Alternating flams', 'The sticking shows the hand that plays the main note. The grace note is played by the other hand.', sub=1, bpm=60, lines=dict(sn='ffff'), st='RLRL', acc='>>>>'),
  E('Flams and taps', 'A flam on the beat, then a single tap.', bpm=60, lines=dict(sn='fofo fofo'), st='RLLR RLLR'),
  TIP('Switch heights', 'After each flam, the hand that played the main note must end low (ready for the next grace note) and the grace-note hand comes up high. The whole rudiment is really about stick heights.'),
),

C(33, 3, 'Flam Taps', 'Flam, tap, flam, tap',
  P('A <b>flam tap</b> is a flam followed by a tap with the same hand as the main note: lR R, rL L. It sounds like a galloping double stroke.'),
  E('Flam taps', None, sub=4, bpm=60, lines=dict(sn='fofo fofo fofo fofo'), st='RRLL RRLL RRLL RRLL', acc='>.>. >.>. >.>. >.>.'),
  E('Flam taps with bass drum', 'Bass drum on every beat under the flam taps.', sub=4, bpm=60, lines=dict(sn='fofo fofo fofo fofo', bd='o... o... o... o...'), st='RRLL RRLL RRLL RRLL'),
  TIP('Two heights, again', 'The main note is high, the tap is low, and the low tap stick then plays the grace note of the next flam. Keep those two heights clear and flam taps become easy.'),
),

C(34, 3, 'The Flam Accent', 'Flam, tap, tap in triplets',
  P('The <b>flam accent</b> is a flam followed by two taps, in triplets: lR L R, rL R L. The flam alternates hands each beat.'),
  E('Flam accents', None, sub=3, bpm=60, lines=dict(sn='foo foo foo foo'), st='RLR LRL RLR LRL', acc='>.. >.. >.. >..'),
  E('With the bass drum', 'Bass drum on every beat under the flams.', sub=3, bpm=60, lines=dict(sn='foo foo foo foo', bd='o.. o.. o.. o..'), st='RLR LRL RLR LRL'),
  TIP('Think single strokes', 'Under the flams, the flam accent is just a single stroke roll in triplets: R L R L R L. The grace notes sit on top.'),
),

C(35, 3, 'The Flamacue', 'Accent on the second note',
  P('The <b>flamacue</b> is a group of four sixteenths starting with a flam, with an unusual <b>accent on the second note</b>, and it ends with another flam on the next beat: lR L R L, lR.'),
  E('Flamacues', 'Accent the second sixteenth, not the flam.', sub=4, bpm=56, lines=dict(sn='fooo f... fooo f...'), st='RLRL R___ LRLR L___', acc='.>.. >... .>.. >...'),
  TIP('Why it’s tricky', 'Your instinct is to accent the flam. Keep the first flam medium, hit the second note hard, then land the final flam firmly on the beat.'),
),

C(36, 3, 'The Drag', 'Two grace notes before the main note',
  P('A <b>drag</b> (also called a ruff) is like a flam with two grace notes instead of one. The two grace notes are a quick, soft double bounce by one hand, followed by the main note in the other: llR, rrL.'),
  E('Alternating drags', None, sub=1, bpm=56, lines=dict(sn='dddd'), st='RLRL', acc='>>>>'),
  E('Drags and taps', None, bpm=56, lines=dict(sn='dodo dodo'), st='RLLR RLLR'),
  TIP('Bounce, don’t play', 'The grace notes should be one relaxed drop that bounces twice. If you try to play two separate strokes they will be too loud and too slow.'),
),

C(37, 3, 'The Single Drag Tap', 'Drag, tap',
  P('The <b>single drag tap</b> is a drag followed by a tap with the other hand: llR L, rrL R. The main note of the drag is accented.'),
  E('Single drag taps', None, bpm=56, lines=dict(sn='dodo dodo'), st='RLLR RLLR', acc='>.>. >.>.'),
  E('Two bars with bass drum', None, bars=2, bpm=56, lines=dict(sn='dodo dodo dodo dodo', bd='o.o. o.o. o.o. o.o.'), st='RLLR RLLR RLLR RLLR'),
  TIP('Accent and tap', 'Big accent on the drag, small tap after it. The contrast is what makes it sound musical.'),
),

C(38, 3, 'The Five-Stroke Roll', 'R R L L R',
  P('A <b>five-stroke roll</b> is two double strokes followed by an accented single: R R L L <b>R</b>. It is written as a note with slashes (the roll) tied to an accented note.'),
  E('Five-stroke rolls', 'Each roll starts on the beat and lands on the &. Then start again with the other hand: LLRR L.', sub=4, bpm=56, lines=dict(sn='w.o. w.o. w.o. w.o.'), st='R_R_ L_L_ R_R_ L_L_', acc='..>. ..>. ..>. ..>.'),
  E('Written out', 'The same roll written as individual notes, slowly. The doubles are 32nd notes; here they are shown as sixteenths at half speed.', sub=4, bpm=50, lines=dict(sn='oooo o... oooo o...'), st='RRLL R___ LLRR L___', acc='.... >... .... >...'),
  TIP('Ends on the accent', 'Every short roll ends with an accented single stroke. Aim for that last note: the doubles just lead into it.'),
),

C(39, 3, 'The Seven-Stroke Roll', 'Three doubles and an accent',
  P('The <b>seven-stroke roll</b> is three doubles and an accent: R R L L R R <b>L</b>. It is a longer version of the five-stroke roll and, because of the odd number of doubles, it ends on the opposite hand.'),
  E('Seven-stroke rolls', 'The roll fills three sixteenths and lands on the a.', sub=4, bpm=52, lines=dict(sn='w..o w..o w..o w..o'), st='R__L L__R R__L L__R', acc='...> ...> ...> ...>'),
  E('Written out', 'Three doubles and a single, at half speed.', sub=4, bars=2, bpm=50, lines=dict(sn='oooo ooo. .... .... oooo ooo. .... ....'), st='RRLL RRL_ ____ ____ LLRR LLR_ ____ ____', acc='.... ..>. .... .... .... ..>. .... ....'),
  TIP('Count the doubles', 'Five-stroke: two doubles. Seven-stroke: three. Nine-stroke: four. The number in the name is always the doubles times two, plus one.'),
),

C(40, 3, 'The Nine-Stroke Roll', 'Four doubles and an accent',
  P('The <b>nine-stroke roll</b> is four doubles and an accented single: R R L L R R L L <b>R</b>. Written as a roll, it lasts one beat and lands on the next.'),
  E('Nine-stroke rolls', 'A quarter-note roll tied into an accent on the next beat.', sub=4, bpm=52, lines=dict(sn='w... o... w... o...'), st='R___ R___ L___ L___', acc='.... >... .... >...'),
  TIP('Even spacing', 'The doubles should sound like one smooth sound, not four separate pairs. Record yourself and listen for gaps.'),
),

C(41, 3, 'The Buzz Roll', 'Multiple-bounce roll',
  P('The <b>buzz roll</b> (or multiple-bounce roll) presses each stroke into the head so it buzzes several times. Alternating buzzing strokes quickly makes a smooth, sustained sound. It is written with a <b>z</b> through the stem.'),
  E('Buzz strokes', 'Each note is one buzz. Press slightly into the head with relaxed fingers.', sub=1, bpm=60, lines=dict(sn='zzzz'), st='RLRL'),
  E('Buzz roll into an accent', 'Buzz for three beats, tie into an accent on 4.', sub=4, bpm=60, lines=dict(sn='z... z... z... o...'), acc='.... .... .... >...'),
  TIP('Same length on both hands', 'The most common problem is one hand buzzing longer than the other. Practice slow buzz strokes, one hand at a time, until they match.'),
),

C(42, 3, 'Single Stroke Four and Seven', 'Quick singles into a beat',
  P('These rudiments are quick bursts of single strokes that land on a beat. <b>Single stroke four</b>: three quick notes into a fourth. <b>Single stroke seven</b>: six quick notes into a seventh.'),
  E('Single stroke four', 'Three triplet notes and a landing note.', sub=3, bpm=60, lines=dict(sn='ooo o.. ooo o..'), st='RLR L__ RLR L__', acc='... >.. ... >..'),
  E('Single stroke seven', 'Six triplet notes and a landing note.', sub=3, bpm=60, lines=dict(sn='ooo ooo o.. ...'), st='RLR LRL R__ ___', acc='... ... >.. ...'),
  TIP('Land on time', 'The last note is the important one. Everything before it is a run-up. If the last note is late, slow the run-up down.'),
),

C(43, 3, 'Accent Patterns', 'Control over every note',
  P('Accent patterns train your hands to play loud and soft notes anywhere. Play each pattern with alternating sticking. The unaccented notes stay low and soft.'),
  E('Accent on 1 and a', None, sub=4, bpm=60, lines=dict(sn='oooo oooo oooo oooo'), st=S16, acc='>..> >..> >..> >..>'),
  E('Accent on e and &', None, sub=4, bpm=60, lines=dict(sn='oooo oooo oooo oooo'), st=S16, acc='.>>. .>>. .>>. .>>.'),
  E('Accents in threes', 'Accent every third sixteenth. The accent shifts through the beat, creating a three-over-four feel.', sub=4, bpm=60, lines=dict(sn='oooo oooo oooo oooo'), st=S16, acc='>..> ..>. .>.. >...'),
  TIP('Move the accents to the kit', 'Once these are even, play the accented notes on a tom or cymbal and the soft notes on the snare. You’ve just made a fill.'),
),

C(44, 3, 'Rudiments Around the Kit', 'From the pad to the drums',
  P('Rudiments become music when you move them around the drum set. Keep the sticking exactly the same; only the drums change.'),
  E('Singles, snare to toms', 'Four sixteenths on each drum, from high to low.', sub=4, bpm=60, lines=dict(sn='oooo .... .... oooo', t1='.... oooo .... ....', t2='.... .... oooo ....', bd='o... o... o... o...'), st=S16),
  E('Paradiddle split', 'Right hand on the floor tom, left on the snare.', sub=4, bpm=60, lines=dict(t2='o.oo .o.. o.oo .o..', sn='.o.. o.oo .o.. o.oo', bd='o... o... o... o...'), st='RLRR LRLL RLRR LRLL'),
  E('Flam accents on the toms', 'Flams on the toms, taps on the snare.', sub=3, bpm=60, lines=dict(t1='f.. ... f.. ...', t2='... f.. ... f..', sn='.oo .oo .oo .oo', bd='o.. o.. o.. o..'), st='RLR LRL RLR LRL'),
  TIP('Stay relaxed moving', 'Moving between drums makes your strokes stiffer. Move from the shoulder and elbow, and let the wrists keep playing the same stroke.'),
),

C(45, 3, 'A Rudiment Routine', 'Ten minutes a day',
  P('You don’t need all forty rudiments every day. This routine covers the main families in about ten minutes. Use the metronome and start slow.'),
  PRACTICE(('2 min', 'Single strokes (Chapter 27), both hands leading.'), ('2 min', 'Double strokes (Chapter 28).'), ('2 min', 'Paradiddles (Chapter 29).'), ('2 min', 'Flam taps or flam accents (Chapters 33–34).'), ('2 min', 'Five- and nine-stroke rolls (Chapters 38 and 40).')),
  E('Warm-up combination', 'Singles, doubles and paradiddles in one exercise.', sub=4, bars=2, bpm=60, lines=dict(sn='oooo oooo oooo oooo oooo oooo oooo oooo'), st='RLRL RLRL RRLL RRLL RLRR LRLL RLRR LRLL', acc='>... >... >... >... >... >... >... >...'),
  TIP('Rotate', 'Pick two or three different rudiments each week to add to the routine. By the end of a few months you will have played them all.'),
),

# ---------------- Part 4: Rock grooves ----------------

C(46, 4, 'The Basic Rock Beat', 'Hi-hat, bass drum, snare',
  P('The <b>basic rock beat</b> is the groove behind thousands of songs. Your right hand plays eighth notes on the hi-hat, your right foot plays the bass drum on 1 and 3, and your left hand plays the snare on 2 and 4.'),
  E('Hi-hat alone', 'Right hand, eighth notes. Count 1 & 2 & 3 & 4 &.', bpm=80, lines=dict(hh='xxxx xxxx')),
  E('Add the bass drum', 'Bass drum on 1 and 3, played together with the hi-hat.', bpm=80, lines=dict(hh='xxxx xxxx', bd='o... o...')),
  E('Add the snare', 'The complete beat: snare on 2 and 4.', bpm=80, lines=dict(hh='xxxx xxxx', sn='..o. ..o.', bd='o... o...')),
  TIP('Build it in layers', 'If the full beat falls apart, go back to the hi-hat alone, then add one limb at a time. This is how every new groove should be learned.'),
),

C(47, 4, 'Bass Drum Variations', 'Moving the right foot',
  P('Keep the hi-hat and snare exactly the same and move the bass drum. Each change gives the groove a new character.'),
  E('Kick on the & of 3', None, bpm=80, lines=dict(hh='xxxx xxxx', sn='..o. ..o.', bd='o... oo..')),
  E('Kick on the & of 2', None, bpm=80, lines=dict(hh='xxxx xxxx', sn='..o. ..o.', bd='o..o o...')),
  E('Kick on the & of 4', 'Pushes into the next bar.', bpm=80, lines=dict(hh='xxxx xxxx', sn='..o. ..o.', bd='o... o..o')),
  E('Two-bar pattern', None, bars=2, bpm=80, lines=dict(hh='xxxx xxxx xxxx xxxx', sn='..o. ..o. ..o. ..o.', bd='o... oo.. o..o o.o.')),
  TIP('Hi-hat on autopilot', 'The hi-hat hand should not change at all when the foot moves. If it does, slow down.'),
),

C(48, 4, 'Snare Variations', 'Beyond 2 and 4',
  P('The backbeat on 2 and 4 is the anchor, but adding an extra snare note here and there creates movement.'),
  E('Snare on the & of 4', None, bpm=80, lines=dict(hh='xxxx xxxx', sn='..o. ..oo', bd='o... o...')),
  E('Snare on the & of 2', None, bpm=80, lines=dict(hh='xxxx xxxx', sn='..oo ..o.', bd='o... o...')),
  E('Two-bar phrase', 'A plain bar, then a bar with extra snare notes.', bars=2, bpm=80, lines=dict(hh='xxxx xxxx xxxx xxxx', sn='..o. ..o. ..o. .oo.', bd='o... o... o... o...')),
  TIP('Less is more', 'Extra notes sound best when they are rare. Play a plain beat for three bars and add the variation in the fourth.'),
),

C(49, 4, 'Quarter-Note Hi-Hat', 'Space for slow songs',
  P('At slow tempos, eighth notes on the hi-hat can sound busy. Playing <b>quarter notes</b> on the hi-hat opens up the groove and is common in ballads.'),
  E('Quarter-note groove', None, sub=2, bpm=70, lines=dict(hh='x.x. x.x.', sn='..o. ..o.', bd='o... o...')),
  E('With kick on the &', None, sub=2, bpm=70, lines=dict(hh='x.x. x.x.', sn='..o. ..o.', bd='o... oo..')),
  TIP('Longer notes, fatter sound', 'With fewer notes, each one matters more. Let the snare ring and don’t rush the space between the beats.'),
),

C(50, 4, 'Riding the Ride Cymbal', 'A bigger, washier sound',
  P('Moving your right hand from the hi-hat to the <b>ride cymbal</b> is an easy way to lift a song, often in the chorus. Play the ride about halfway between the bell and the edge.'),
  E('Ride groove', None, bpm=84, lines=dict(rd='xxxx xxxx', sn='..o. ..o.', bd='o... oo..')),
  E('Ride with hi-hat foot', 'Keep time on the hi-hat pedal on 2 and 4 while riding.', bpm=84, lines=dict(rd='xxxx xxxx', sn='..o. ..o.', bd='o... oo..', hf='..x. ..x.')),
  E('Crash into the ride', 'Start the section with a crash on 1.', bars=2, bpm=84, lines=dict(cr='x... .... .... ....', rd='.xxx xxxx xxxx xxxx', sn='..o. ..o. ..o. ..o.', bd='o... o... o... o...')),
  TIP('Match the volume', 'The ride is louder than a closed hi-hat. Play it more softly so the snare and bass drum still come through.'),
),

C(51, 4, 'Sixteenth-Note Hi-Hat, One Hand', 'Driving sixteenths',
  P('At slow and medium tempos, the right hand can play <b>sixteenth notes</b> on the hi-hat by itself. The left hand still plays the snare on 2 and 4.'),
  E('One-hand sixteenths', 'Right hand only on the hi-hat.', sub=4, bpm=66, lines=dict(hh='xxxx xxxx xxxx xxxx', sn='.... o... .... o...', bd='o... .... o... ....')),
  E('Accent the eighths', 'Accent the hi-hat on the numbers and &s for a stronger feel.', sub=4, bpm=66, lines=dict(hh='xxxx xxxx xxxx xxxx', sn='.... o... .... o...', bd='o... .... o.o. ....'), acc='>.>. >.>. >.>. >.>.'),
  TIP('Small strokes', 'Keep the hi-hat strokes small and close to the cymbal. Big strokes at this speed will wear you out.'),
),

C(52, 4, 'Sixteenth-Note Bass Drum', 'Syncopated kicks',
  P('With eighth notes on the hi-hat, the bass drum can play on the <b>e</b> or <b>a</b> of the beat, between the hi-hat notes. These kicks give rock and funk grooves their bounce.'),
  E('Kick on the a of 2', None, sub=4, bpm=70, lines=dict(hh='x.x. x.x. x.x. x.x.', sn='.... o... .... o...', bd='o... ...o o... ....')),
  E('Kick on the a of 1', None, sub=4, bpm=70, lines=dict(hh='x.x. x.x. x.x. x.x.', sn='.... o... .... o...', bd='o..o .... o... ....')),
  E('Kick on the e of 3', None, sub=4, bpm=70, lines=dict(hh='x.x. x.x. x.x. x.x.', sn='.... o... .... o...', bd='o... .... oo.. ....')),
  TIP('Count the gaps', 'The hard part is kicks that fall between hi-hat notes. Count sixteenths out loud and move your hand in the air for the missing sixteenths if it helps.'),
),

C(53, 4, 'Open Hi-Hat', 'Adding sizzle',
  P('A small <b>o</b> over a hi-hat note means open: lift your foot so the cymbals ring. The next closed note (or a hi-hat foot) closes it again. Open hi-hats on the &s give a groove lift.'),
  E('Open on the & of 4', None, bpm=84, lines=dict(hh='xxxx xxxO', sn='..o. ..o.', bd='o... o...')),
  E('Open on the & of 2 and 4', None, bpm=84, lines=dict(hh='xxxO xxxO', sn='..o. ..o.', bd='o... o...')),
  E('Open with the kick', None, bpm=84, lines=dict(hh='xxxx xOxx', sn='..o. ..o.', bd='o... oo..')),
  TIP('Close on time', 'The open sound should stop exactly on the next count. Press your foot down right as the next hi-hat note is played.'),
),

C(54, 4, 'Four on the Floor', 'Disco and dance grooves',
  P('In <b>four on the floor</b>, the bass drum plays every beat. With open hi-hats on the &s, it becomes the classic disco and dance groove.'),
  E('Four on the floor', None, bpm=110, lines=dict(hh='xxxx xxxx', sn='..o. ..o.', bd='o.o. o.o.')),
  E('Disco', 'Open hi-hat on every &, closed on the beat.', bpm=110, lines=dict(hh='xOxO xOxO', sn='..o. ..o.', bd='o.o. o.o.')),
  TIP('A steady foot', 'Four on the floor exposes any unevenness in your bass drum. Practice with the metronome until every kick lines up with the click.'),
),

C(55, 4, 'Half-Time Feel', 'Snare on 3',
  P('In a <b>half-time</b> groove the snare plays only on beat 3. The tempo stays the same but the music feels twice as slow and heavy.'),
  E('Half-time', None, bpm=80, lines=dict(hh='xxxx xxxx', sn='.... o...', bd='o... ..o.')),
  E('Half-time with sixteenth hats', None, sub=4, bpm=70, lines=dict(hh='xxxx xxxx xxxx xxxx', sn='.... .... o... ....', bd='o... .... .... ..o.')),
  TIP('Hear the difference', 'Play four bars of the basic rock beat, then four bars of half-time at the same tempo. The song seems to slow down even though the click doesn’t.'),
),

C(56, 4, 'Double-Time Feel', 'Fast punk and polka beats',
  P('In a <b>double-time</b> feel, the snare moves to every &: the bass drum on the beat, the snare on the off-beat. It is the driving beat of punk rock and fast country.'),
  E('Double-time', None, bpm=100, lines=dict(hh='xxxx xxxx', sn='.o.o .o.o', bd='o.o. o.o.')),
  E('Double-time, quarter-note hi-hat', None, bpm=140, lines=dict(hh='x.x. x.x.', sn='.o.o .o.o', bd='o.o. o.o.')),
  TIP('Stay loose at speed', 'Fast tempos need relaxed muscles. If your arms burn, slow down and focus on smaller strokes.'),
),

C(57, 4, 'Two-Handed Sixteenth Grooves', 'Alternating on the hi-hat',
  P('At faster tempos, play the hi-hat sixteenths with <b>both hands</b>: R L R L. On beats 2 and 4, the right hand moves to the snare while the left keeps going on the hi-hat.'),
  E('Two-handed groove', 'The right hand leaves the hi-hat to play the backbeat.', sub=4, bpm=84, lines=dict(hh='xxxx .xxx xxxx .xxx', sn='.... o... .... o...', bd='o... .... o.o. ....'), st=S16),
  TIP('Funk and disco favorite', 'This technique is behind many disco and funk grooves. Keep the left hand soft and steady; it is the engine.'),
),

C(58, 4, 'Tom Grooves', 'The floor tom beat',
  P('Move the right hand from the hi-hat to the <b>floor tom</b> and the groove becomes big and tribal. It is a common sound in rock ballads and anthems.'),
  E('Floor tom groove', None, bpm=84, lines=dict(t2='oooo oooo', sn='..o. ..o.', bd='o... o...')),
  E('Toms and kick together', 'Accented floor tom with bass drum on the beats.', bpm=90, lines=dict(t2='o.oo o.oo', sn='..o. ..o.', bd='o.o. o.o.'), acc='>... >...'),
  TIP('Let it ring', 'The floor tom sustains longer than a hi-hat. Play a little softer so the sound doesn’t turn into mush.'),
),

C(59, 4, 'Crashes and Song Sections', 'Marking the form',
  P('Drummers use the <b>crash cymbal</b> to mark the start of new sections: verse, chorus, bridge. The crash is almost always played together with the bass drum on beat 1.'),
  E('Crash on the 1', 'Crash on beat 1 of the first bar, then back to the hi-hat.', bars=2, bpm=84, lines=dict(cr='x... .... .... ....', hh='.xxx xxxx xxxx xxxx', sn='..o. ..o. ..o. ..o.', bd='o... o... o... o...')),
  E('Set-up and crash', 'A snare on the & of 4 sets up the crash in the next bar.', bars=2, bpm=84, lines=dict(cr='.... .... x... ....', hh='xxxx xxx. .xxx xxxx', sn='..o. ..oo ..o. ..o.', bd='o... o... o... o...')),
  TIP('Know the form', 'Listen to a song and count the bars of each section. Most sections are 4, 8 or 16 bars long. Crash where the new section starts.'),
),

C(60, 4, 'Rock Groove Workout', 'Putting it together',
  P('This chapter combines the grooves from Part 4 into longer phrases. Play each one for several minutes without stopping.'),
  E('Verse and chorus', 'Hi-hat for the verse, ride for the chorus.', bars=2, bpm=88, lines=dict(hh='xxxx xxxx .... ....', cr='.... .... x... ....', rd='.... .... .xxx xxxx', sn='..o. ..o. ..o. ..o.', bd='o... oo.. o... oo..')),
  E('Groove and fill', 'Three beats of groove and a sixteenth-note fill on the snare.', sub=4, bars=2, bpm=80, lines=dict(hh='x.x. x.x. x.x. .... .... x.x. x.x. x.x.', cr='.... .... .... .... x... .... .... ....', sn='.... o... .... oooo .... o... .... o...', bd='o... .... o.o. .... o... .... o.o. ....')),
  E('Half-time into full time', None, bars=2, bpm=84, lines=dict(hh='xxxx xxxx xxxx xxxx', sn='.... o... ..o. ..o.', bd='o... ..o. o... o...')),
  PRACTICE(('5 min', 'Basic rock beat with bass drum variations.'), ('5 min', 'Open hi-hat and four on the floor.'), ('5 min', 'Half-time and double-time.'), ('5 min', 'Play along with a favourite rock song.')),
),
]
