backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:

  - name: "films"
    label: "Films"
    folder: "content/films"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Film Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Video Link", name: "video", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Project Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Story", name: "body", widget: "markdown" }

  - name: "images"
    label: "Historical Images"
    folder: "content/images"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Upload Image", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }
